apiVersion: apps/v1
kind: deployment
metadata:
  name: app1
  labels: 
    name: app1
    tier: frontend
spec:
  replicas: 1
  selector: 
  matchLabels:
      tier: frontend
      name: app1
  template: 
    metadata:
      labels:
        tier: frontend
        name: app1
    spec:
      containers:
      - name: app1
        image: raidi/app1:v1
---
apiVersion : v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    tier: frontend
    name: app1
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 #container port